# Site settings
title: 크림슨풋의 개발 성장기
description: > # this means to ignore newlines until "baseurl:"
  CrimsonFoot's Growth
permalink: ":title/"
baseurl: "https://tksuns12.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 강현길 # add your name
author-img: "/assets/logo.png"
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: tksuns12
social-linkedin: # add your Linkedin handle
social-email: tksuns@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
